FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p media

# Run migrations
RUN python manage.py migrate

ENV PYTHONUNBUFFERED=1

EXPOSE 7860

CMD ["python", "manage.py", "runserver", "0.0.0.0:7860"]
